package actor

import (
	"github.com/ray/goreact/pkg/core"
)

// Actor represents the "Hands" of the ReAct engine.
// It is the component capable of interacting with the physical or digital environment
// by executing tools, sandbox scripts, or hitting external APIs.
type Actor interface {
	// Act executes the last proposed Action generated by the Thinker.
	// It extracts the Action from ctx.LastTrace().Action, maps it to an underlying 
	// tool/skill, manages concurrent execution if necessary, and captures 
	// the raw, unprocessed result or error.
	//
	// It is crucial that Actor handles internal local retries and timeout boundaries.
	// The results of this execution are expected to be temporarily stored
	// back into the context or directly pipelined into the Observer.
	Act(ctx *core.PipelineContext) error
}
