package parser

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"github.com/ray/goreact/pkg/core"
)

var (
	// regex mappings for extracting blocks from LLM raw text
	thoughtRegex     = regexp.MustCompile(`(?ms)Thought:\s*(.*?)(?:\nAction:|\nFinalAnswer:|$)`)
	actionRegex      = regexp.MustCompile(`(?m)^Action:\s*([^\n]+)`)
	actionInputRegex = regexp.MustCompile(`(?ms)ActionInput:\s*(.*?)(?:\nObservation:|\nThought:|$)`)
	finalAnswerRegex = regexp.MustCompile(`(?ms)FinalAnswer:\s*(.*)`)
)

// ParseLLMOutput evaluates the raw text generated by the large language model
// and constructs a cognitive Trace or finishes the session.
func ParseLLMOutput(raw string) (trace *core.Trace, finalResult string, isFinished bool, err error) {
	// First check if LLM believes the task is complete
	if match := finalAnswerRegex.FindStringSubmatch(raw); len(match) > 1 {
		finalResult = strings.TrimSpace(match[1])
		
		// Optional: also extract final thought if it exists before FinalAnswer
		thought := ""
		if tMatch := thoughtRegex.FindStringSubmatch(raw); len(tMatch) > 1 {
			thought = strings.TrimSpace(tMatch[1])
		}
		
		return &core.Trace{Thought: thought}, finalResult, true, nil
	}

	// It didn't finish. Attempt to parse ReAct Action blocks
	thoughtMatch := thoughtRegex.FindStringSubmatch(raw)
	actionMatch := actionRegex.FindStringSubmatch(raw)
	inputMatch := actionInputRegex.FindStringSubmatch(raw)

	if len(actionMatch) < 2 || len(inputMatch) < 2 {
		return nil, "", false, fmt.Errorf("could not parse valid Action or ActionInput from LLM output: %s", raw)
	}

	thought := ""
	if len(thoughtMatch) > 1 {
		thought = strings.TrimSpace(thoughtMatch[1])
	}
	
	actionName := strings.TrimSpace(actionMatch[1])
	rawInput := strings.TrimSpace(inputMatch[1])

	// Remove common markdown json wrapper if the LLM leaked it
	rawInput = strings.TrimPrefix(rawInput, "```json")
	rawInput = strings.TrimPrefix(rawInput, "```")
	rawInput = strings.TrimSuffix(rawInput, "```")
	rawInput = strings.TrimSpace(rawInput)

	var parsedInput map[string]interface{}
	if rawInput != "" {
		if err := json.Unmarshal([]byte(rawInput), &parsedInput); err != nil {
			return nil, "", false, fmt.Errorf("failed to parse ActionInput as JSON: %w", err)
		}
	} else {
		parsedInput = make(map[string]interface{})
	}

	trace = &core.Trace{
		Thought: thought,
		Action: &core.Action{
			Name:  actionName,
			Input: parsedInput,
		},
	}

	return trace, "", false, nil
}
