package parser

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"github.com/DotNetAge/goreact/pkg/core"
)

var (
	// regex mappings for extracting blocks from LLM raw text
	thoughtRegex     = regexp.MustCompile(`(?ms)Thought:\s*(.*?)(?:\nAction:|\nFinalAnswer:|$)`)
	actionRegex      = regexp.MustCompile(`(?m)^Action:\s*([^\n]+)`)
	actionInputRegex = regexp.MustCompile(`(?ms)ActionInput:\s*(.*?)(?:\nObservation:|\nThought:|$)`)
	finalAnswerRegex = regexp.MustCompile(`(?ms)FinalAnswer:\s*(.*)`)
)

// ParseLLMOutput evaluates the raw text generated by the large language model
// and constructs a cognitive Trace or finishes the session.
func ParseLLMOutput(raw string) (trace *core.Trace, finalResult string, isFinished bool, err error) {
	// First check if LLM believes the task is complete
	if match := finalAnswerRegex.FindStringSubmatch(raw); len(match) > 1 {
		finalResult = strings.TrimSpace(match[1])

		// Optional: also extract final thought if it exists before FinalAnswer
		thought := ""
		if tMatch := thoughtRegex.FindStringSubmatch(raw); len(tMatch) > 1 {
			thought = strings.TrimSpace(tMatch[1])
		}

		return &core.Trace{Thought: thought}, finalResult, true, nil
	}

	// It didn't finish. Attempt to parse ReAct Action blocks
	thoughtMatch := thoughtRegex.FindStringSubmatch(raw)
	actionMatch := actionRegex.FindStringSubmatch(raw)
	inputMatch := actionInputRegex.FindStringSubmatch(raw)

	if len(actionMatch) < 2 || len(inputMatch) < 2 {
		return nil, "", false, fmt.Errorf("could not parse valid Action or ActionInput from LLM output: %s", raw)
	}

	thought := ""
	if len(thoughtMatch) > 1 {
		thought = strings.TrimSpace(thoughtMatch[1])
	}

	actionName := strings.TrimSpace(actionMatch[1])
	rawInput := strings.TrimSpace(inputMatch[1])

	// Remove common markdown json wrapper if the LLM leaked it
	rawInput = strings.TrimPrefix(rawInput, "```json")
	rawInput = strings.TrimPrefix(rawInput, "```")
	rawInput = strings.TrimSuffix(rawInput, "```")
	rawInput = strings.TrimSpace(rawInput)

	var parsedInput map[string]any
	if rawInput != "" {
		if err := json.Unmarshal([]byte(rawInput), &parsedInput); err != nil {
			return nil, "", false, fmt.Errorf("failed to parse ActionInput as JSON: %w", err)
		}
	} else {
		parsedInput = make(map[string]any)
	}

	trace = &core.Trace{
		Thought: thought,
		Action: &core.Action{
			Name:  actionName,
			Input: parsedInput,
		},
	}

	return trace, "", false, nil
}

// TaskType represents the logical nature of a planned task.
type TaskType string

const (
	TaskSequence TaskType = "sequence"
	TaskIf       TaskType = "if"
	TaskLoop     TaskType = "loop"
)

// PlannedTask represents a single logical unit in a generated plan.
type PlannedTask struct {
	Type      TaskType
	StepName  string
	Task      string
	Condition string // For If/Loop
	Then      string // For If
	Else      string // For If
}

// ParsePlan extracts a structured task flow from the LLM's planning output.
// It looks for patterns like "Step N:", "If [cond] Then", "Repeat [task] Until".
func ParsePlan(raw string) ([]PlannedTask, error) {
	var tasks []PlannedTask
	lines := strings.Split(raw, "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		// 1. Match Sequence: "Step 1: Analyze data"
		if strings.HasPrefix(strings.ToLower(line), "step") {
			parts := strings.SplitN(line, ":", 2)
			if len(parts) == 2 {
				tasks = append(tasks, PlannedTask{
					Type:     TaskSequence,
					StepName: strings.TrimSpace(parts[0]),
					Task:     strings.TrimSpace(parts[1]),
				})
			}
			continue
		}

		// 2. Match If: "If [file exists] then [read file] else [create file]"
		if strings.HasPrefix(strings.ToLower(line), "if") {
			// Basic heuristic parsing for the demo/prototype
			tasks = append(tasks, PlannedTask{
				Type: TaskIf,
				Task: line,
			})
			continue
		}

		// 3. Match Loop: "Repeat [check status] until [success]"
		if strings.HasPrefix(strings.ToLower(line), "repeat") || strings.HasPrefix(strings.ToLower(line), "loop") {
			tasks = append(tasks, PlannedTask{
				Type: TaskLoop,
				Task: line,
			})
			continue
		}
	}

	if len(tasks) == 0 {
		return nil, fmt.Errorf("no structured tasks found in plan")
	}

	return tasks, nil
}
