// Package tool provides tool interfaces and implementations for the goreact framework.
package tool

import (
	"context"

	"github.com/DotNetAge/goreact/pkg/common"
)

// Node interface that tools must satisfy for memory indexing
type Node interface {
	// Name returns the node name (unique identifier)
	Name() string
	// Type returns the node type
	Type() string
	// Properties returns the node properties
	Properties() map[string]any
}

// Tool represents an executable tool
type Tool interface {
	// Node interface - tools are resources that can be indexed by Memory
	Node
	// Description returns the tool description
	Description() string
	// SecurityLevel returns the security level
	SecurityLevel() common.SecurityLevel
	// IsIdempotent returns whether the tool is idempotent
	IsIdempotent() bool
	// Run executes the tool
	Run(ctx context.Context, params map[string]any) (any, error)
}

// ToolInfo represents tool metadata
type ToolInfo struct {
	// Name is the tool name
	Name string `json:"name" yaml:"name"`
	
	// Description is the tool description
	Description string `json:"description" yaml:"description"`
	
	// SecurityLevel is the security level
	SecurityLevel common.SecurityLevel `json:"security_level" yaml:"security_level"`
	
	// IsIdempotent indicates if the tool is idempotent
	IsIdempotent bool `json:"is_idempotent" yaml:"is_idempotent"`
	
	// Parameters are the tool parameters
	Parameters []Parameter `json:"parameters" yaml:"parameters"`
	
	// ReturnType is the return type
	ReturnType string `json:"return_type" yaml:"return_type"`
	
	// Examples are usage examples
	Examples []string `json:"examples" yaml:"examples"`
}

// Parameter represents a tool parameter
type Parameter struct {
	// Name is the parameter name
	Name string `json:"name" yaml:"name"`
	
	// Type is the parameter type
	Type string `json:"type" yaml:"type"`
	
	// Required indicates if the parameter is required
	Required bool `json:"required" yaml:"required"`
	
	// Default is the default value
	Default any `json:"default" yaml:"default"`
	
	// Description is the parameter description
	Description string `json:"description" yaml:"description"`
	
	// Enum is the list of allowed values
	Enum []any `json:"enum" yaml:"enum"`
}

// BaseTool provides a base implementation for tools
type BaseTool struct {
	name          string
	description   string
	securityLevel common.SecurityLevel
	idempotent    bool
	parameters    []Parameter
}

// Name returns the tool name (implements Node)
func (t *BaseTool) Name() string {
	return t.name
}

// Type returns the node type (implements Node)
func (t *BaseTool) Type() string {
	return "tool"
}

// Properties returns the node properties (implements Node)
func (t *BaseTool) Properties() map[string]any {
	return map[string]any{
		"description":     t.description,
		"security_level":  t.securityLevel.String(),
		"is_idempotent":   t.idempotent,
		"parameters":      t.parameters,
	}
}

// Description returns the tool description
func (t *BaseTool) Description() string {
	return t.description
}

// SecurityLevel returns the security level
func (t *BaseTool) SecurityLevel() common.SecurityLevel {
	return t.securityLevel
}

// IsIdempotent returns whether the tool is idempotent
func (t *BaseTool) IsIdempotent() bool {
	return t.idempotent
}

// Parameters returns the tool parameters
func (t *BaseTool) Parameters() []Parameter {
	return t.parameters
}

// NewBaseTool creates a new BaseTool
func NewBaseTool(name, description string, securityLevel common.SecurityLevel, idempotent bool) *BaseTool {
	return &BaseTool{
		name:          name,
		description:   description,
		securityLevel: securityLevel,
		idempotent:    idempotent,
		parameters:    []Parameter{},
	}
}

// WithParameter adds a parameter
func (t *BaseTool) WithParameter(param Parameter) *BaseTool {
	t.parameters = append(t.parameters, param)
	return t
}

// ToolNode represents a Tool node in the memory graph
type ToolNode struct {
	Name           string                  `json:"name" yaml:"name"`
	NodeType       string                  `json:"node_type" yaml:"node_type"`
	Description    string                  `json:"description" yaml:"description"`
	Type           common.ToolType         `json:"type" yaml:"type"`
	Schema         map[string]any          `json:"schema" yaml:"schema"`
	Endpoint       string                  `json:"endpoint" yaml:"endpoint"`
	SecurityLevel  common.SecurityLevel    `json:"security_level" yaml:"security_level"`
	IsIdempotent   bool                    `json:"is_idempotent" yaml:"is_idempotent"`
	ExecutionCount int                     `json:"execution_count" yaml:"execution_count"`
	SuccessRate    float64                 `json:"success_rate" yaml:"success_rate"`
}

// GeneratedTool represents a tool generated by evolution
type GeneratedTool struct {
	// Name is the tool name
	Name string `json:"name" yaml:"name"`
	
	// Description is the tool description
	Description string `json:"description" yaml:"description"`
	
	// FilePath is the file path where the tool is saved
	FilePath string `json:"file_path" yaml:"file_path"`
	
	// Type is the tool type
	Type common.ToolType `json:"type" yaml:"type"`
	
	// Parameters are the tool parameters
	Parameters []Parameter `json:"parameters" yaml:"parameters"`
	
	// ReturnType is the return type
	ReturnType string `json:"return_type" yaml:"return_type"`
	
	// SecurityLevel is the security level
	SecurityLevel common.SecurityLevel `json:"security_level" yaml:"security_level"`
	
	// Code is the generated code
	Code string `json:"code" yaml:"code"`
	
	// CreatedAt is the creation timestamp
	CreatedAt string `json:"created_at" yaml:"created_at"`
	
	// SourceSession is the source session
	SourceSession string `json:"source_session" yaml:"source_session"`
	
	// Status is the generation status
	Status common.GeneratedStatus `json:"status" yaml:"status"`
}

// ToolParameter represents a parameter for generated tool
type ToolParameter struct {
	// Name is the parameter name
	Name string `json:"name" yaml:"name"`
	
	// Type is the parameter type
	Type string `json:"type" yaml:"type"`
	
	// Description is the parameter description
	Description string `json:"description" yaml:"description"`
	
	// Required indicates if the parameter is required
	Required bool `json:"required" yaml:"required"`
	
	// Default is the default value
	Default string `json:"default" yaml:"default"`
}

// GetToolInfo returns the tool info
func GetToolInfo(t Tool) *ToolInfo {
	info := &ToolInfo{
		Name:           t.Name(),
		Description:    t.Description(),
		SecurityLevel:  t.SecurityLevel(),
		IsIdempotent:   t.IsIdempotent(),
		Parameters:     []Parameter{},
		Examples:       []string{},
	}
	
	return info
}
