package core

// TokenUsage holds the cumulative tokens consumed across the entire session lifecycle.
type TokenUsage struct {
	PromptTokens     int // Tokens consumed by system instructions and chat history context
	CompletionTokens int // Tokens generated by the model's reasoning and responses
	TotalTokens      int
}

// Add safely accumulates token metrics.
func (u *TokenUsage) Add(prompt, completion int) {
	u.PromptTokens += prompt
	u.CompletionTokens += completion
	u.TotalTokens = u.PromptTokens + u.CompletionTokens
}
